# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Set up test coverage and reporter
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: Build
      run: dotnet build --no-restore
    - name: Test and generate coverage
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage;Format=opencover"
    - name: Run coverage report generation
      run: reportgenerator -reports:"**/coverage*.xml" -targetdir:"coveragereport" -reporttypes:Html
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./coveragereport
